### PR TITLE
PR check: Fix bugs for checkver

### PR DESCRIPTION
**Pull request by LazyGeniusMan**
Try to fix https://github.com/ScoopInstaller/Versions/pull/356 and https://github.com/ScoopInstaller/Extras/pull/7586

### CODE REVIEW

**Comment by LazyGeniusMan** [comment]
Could also use something like `"$manifest.Basename: \n$($object.version)"` for `-match` regex to match manifest name and version

**Comment by LazyGeniusMan** [comment]
It's worked, check this:
https://github.com/LazyGeniusMan/Extras/pull/1#issuecomment-1000921479
https://github.com/LazyGeniusMan/Extras/actions/runs/1620056599/workflow

**Comment by LazyGeniusMan** [comment]
Ahh, I see why it's failed, `$object.version` value is old version, what's the variable for new version detected by checkver?

**Comment by LazyGeniusMan** [comment]
Alright, it's done, sorry it's a messed up commits in PR. What I did is:
- Make a new variable that convert `$outputV` from multi line (array) into single line (string)
- Try to match those converted output with regex of `<manifest-name>: <version>`

### Test 1
Positive test (must passed)
- https://github.com/LazyGeniusMan/Extras/actions/runs/1621822668
- https://github.com/LazyGeniusMan/Extras/pull/1#issuecomment-1001018174
### Test 2
Negative test (must failed), wrong version
- https://github.com/LazyGeniusMan/Extras/actions/runs/1621823212
- https://github.com/LazyGeniusMan/Extras/pull/2#issuecomment-1001018227
### Test 3
Negative test (must failed), wrong URL
- https://github.com/LazyGeniusMan/Extras/actions/runs/1621823509
- https://github.com/LazyGeniusMan/Extras/pull/3#issuecomment-1001018228

**Comment by LazyGeniusMan** [comment]
Let me know if `$outputV.Count -ge 2` is still necessary

**Comment by issaclin32** [comment]
I appreciate your effort, but I don't think removing this check entirely is a good thing. The proper way to solve the problem is to determine errors by another means (e.g. return code of a function).

Before we fix this, our maintainers can just ignore PR check fails for *checkver*, if we know what is going on.

**Comment by LazyGeniusMan** [comment]
> but I don't think removing this check entirely is a good thing

Could you elaborate removing which check? I replaced it with another check which passed test all scenario that I can think of:
- Correct URL and correct version found
- Correct URL but wrong version found (not latest version)
- Wrong URL so version not found

**Comment by issaclin32** [comment]
> Could you elaborate removing which check? I replaced it with another check which passed test all scenario that I can think of:
> 
> * Correct URL and correct version found
> * Correct URL but wrong version found (not latest version)
> * Wrong URL so version not found

Sorry I was wrong. I did not think thoroughly. If `Wrong URL so version not found` is the case, then `package: version` will not appear at all. So there is no problem removing this part.

```
# If there are more than 2 lines and second line is not version, there is problem
$checkver = ((($outputV.Count -ge 2) -and ($outputV[1] -like "$($object.version)")))
```

**Review by issaclin32 — APPROVED** [review]

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
