### PR TITLE
Push hash-fix instead of making a PR

### PR DESCRIPTION
**Pull request by rashil2000**
Will save a good amount of time :)

Tested here - https://github.com/rashil2000/Extras/commits/master

Issues got closed automatically - https://github.com/rashil2000/Extras/issues?q=is%3Aissue+is%3Aclosed

### CODE REVIEW

**Comment by issaclin32** [comment]
Thumbs up for this improvement.

IMO, It would be better to add an extra check for file sizes, e.g. The file should not be less than 100KB, to avoid corrupted files when the link is invalid redirected to a web page.

**Review by issaclin32 — APPROVED** [review]

**Comment by rashil2000** [comment]
> It would be better to add an extra check for file sizes, e.g. The file should not be less than 100KB, to avoid corrupted files when the link is invalid redirected to a web page.

I don't quite get it, which files?

**Comment by issaclin32** [comment]
I mean the archive/installer in manifest's `url`.

Sometimes the developer of the software changes the **file url**, which causes the page to be redirected to a **404 page**, **homepage** or something else.
This will obviously cause installation to fail if we straight up corrects the hash.

**Comment by rashil2000** [comment]
> Sometimes the developer of the software changes the file url, which causes the page to be redirected to a 404 page, homepage or something else.
This will obviously cause installation to fail if we straight up corrects the hash.

Have we seen such a case? It will be better to discuss this in an issue here - since it's not directly related to this PR.

I was under the impression that Scoop will not download/throw an error if it detects a 404, to prevent downloading a webpage.

**Pull request merged**
